export const ADD_STUDENTS = "ADD_STUDENTS"
export const FETCH_STUDENTS = "FETCH_STUDENTS"
export const UPDATE_STUDENTS = "UPDATE_STUDENTS"
export const DELETE_STUDENTS = "DELETE_STUDENTS"

export default { ADD_STUDENTS, FETCH_STUDENTS, UPDATE_STUDENTS, DELETE_STUDENTS };